image: openjdk:17-slim

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - gradle
        script:
          - rm -rf node_modules package-lock.json
          - apt-get update && apt-get install -y findutils
          - apt install -y curl software-properties-common
          - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg
          - echo "deb [signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] https://deb.nodesource.com/node_20.x $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/nodesource.list
          - apt update
          - apt install -y nodejs
          - chmod +x gradlew
          - ./gradlew clean build

  branches:
    master:
      - step:
          name: Deploy to Production
          caches:
            - gradle
          script:
            - apt-get update && apt-get install -y findutils
            - chmod +x gradlew
            - ./gradlew clean build
