image: openjdk:17-slim

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - gradle
        script:
          - apt-get update && apt-get install -y xargs
          - chmod +x gradlew
          - ./gradlew clean build

  branches:
    master:
      - step:
          name: Deploy to Production
          caches:
            - gradle
          script:
            - apt-get update && apt-get install -y xargs
            - chmod +x gradlew
            - ./gradlew clean build
