image: openjdk:17

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - gradle
        script:
          - chmod +x gradlew
          - ./gradlew clean build

  branches:
    master:
      - step:
          name: Deploy to Production
          caches:
            - gradle
          script:
            - chmod +x gradlew
            - ./gradlew clean build
            - ./deploy.sh # Replace with your deployment script
