spring:
  security:
    user:
      name: admin
      password: $2a$10$IRnZTOm/slNNBGyA3ySoHORJtB1QzuvvnJk29ov29WyTsdSoONVN2
  flyway:
    enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false # delaying connection acquisition turn of auto commit mode
      connection-timeout: 30000
      idleTimeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
jwt:
  issuer: errabi
  key-id: 123
  expiry-time: 3600000 #1h