drop table if exists api cascade ;
create table api (
    version integer not null,
    visibility boolean not null,
    created timestamp(6),
    id bigint generated by default as identity,
    last_modified timestamp(6),
    module_id bigint,
    color varchar(255),
    created_by varchar(255),
    description varchar(255),
    enabled boolean not null,
    http_verb varchar(255),
    last_modified_by varchar(255),
    name varchar(255),
    open_api_schema varchar(255),
    url varchar(255),
    primary key (id)
);
