drop table if exists configurations cascade;
create table configurations (
    id bigint generated by default as identity,
    config_key varchar(255),
    config_value varchar(255),
    primary key (id)
);