drop table if exists users cascade;
create table users (
    account_non_expired boolean not null,
    account_non_locked boolean not null,
    credentials_non_expired boolean not null,
    enabled boolean not null,
    id bigint generated by default as identity,
    workspace_id bigint,
    address varchar(255), email varchar(255),
    first_name varchar(255), last_name varchar(255),
    password varchar(255), phone varchar(255),
    username varchar(255),
    primary key (id)
);