drop table if exists audit cascade;
create table audit (
    version integer not null,
    id bigint generated by default as identity,
    time_stamps timestamp(6),
    component varchar(255),
    data varchar(255),
    user_name varchar(255),
    primary key (id)
);