spring:
  security:
    user:
      name: admin
      password: $2a$10$IRnZTOm/slNNBGyA3ySoHORJtB1QzuvvnJk29ov29WyTsdSoONVN2
  flyway:
    enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false # delaying connection acquisition from the connection pool turn of auto commit mode
      connection-timeout: 30000
      idleTimeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        connection:
          autocommit: false
        format_sql: true
        #generate_statistics: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
jwt:
  issuer: errabi
  key-id: 123
  expiry-time: 3600000 #1h

management:
  health:
    mail:
      enabled: false
logging:
  level:
    com:
      zaxxer:
        hikari: TRACE # turn on hikari connection pool logging ,each 30s logs the status of the connection pool in the console
#    org:
#      springframework:
#        orm:
#          jpa: debug #logging transaction details
#        transaction: debug #logging transaction details
      hibernate:
        orm:
          jdbc:
            bind : trace # to display hibernate 6 binding parameters