apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapi-gui-backend-deployment
  namespace: dev
  labels:
    app: openapi-gui-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapi-gui-backend
  template:
    metadata:
      labels:
        app: openapi-gui-backend
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: openapi-gui-backend
          image: europe-southwest1-docker.pkg.dev/sandbox-431715/openapi-ui/openapi-gui-backend:1.1.6
          imagePullPolicy: Always
          env:
            - name: DB_DRIVER
              valueFrom:
                    configMapKeyRef:
                        name: openapi-ui-config
                        key: DB_DRIVER
            - name: DB_URL
              valueFrom:
                    configMapKeyRef:
                        name: openapi-ui-config
                        key: DB_URL
            - name: DB_USER
              valueFrom:
                  configMapKeyRef:
                        name: openapi-ui-config
                        key: DB_USER
            - name: DB_PASS
              valueFrom:
                    configMapKeyRef:
                        name: openapi-ui-config
                        key: DB_PASS
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"