apiVersion: v1
kind: Service
metadata:
  name: openapi-gui-backend-service
  namespace: dev
spec:
  selector:
    app: openapi-gui-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080