drop table if exists server cascade ;
create table server (
                        id bigint generated by default as identity,
                        description varchar(255),
                        url varchar(255),
                        primary key (id)
);