apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openapi-ui-db-pvc-volume
  namespace: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
