apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapi-gui-deployment
  namespace: dev
  labels:
    app: openapi-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapi-gui
  template:
    metadata:
      labels:
        app: openapi-gui
    spec:
      containers:
        - name: openapi-gui
          image: europe-southwest1-docker.pkg.dev/sandbox-431715/openapi-ui/openapi-ui:1.1.5-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
               cpu: "250m"
               memory: "500Mi"
            limits:
               cpu: "1"
               memory: "1Gi"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8080
#            initialDelaySeconds: 3000
#            periodSeconds: 2000
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#            initialDelaySeconds: 1500
#            periodSeconds: 10000