apiVersion: v1
kind: PersistentVolume
metadata:
  name: openapi-ui-db-pv-volume
  namespace: dev
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
