---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "openapi-gui-ingress"
  namespace: "dev"
spec:
  defaultBackend:
    service:
      name: "openapi-gui-service"
      port:
        number: 80
status:
  loadBalancer: {}
